### ISSUE TITLE
changes on the splash page

### ISSUE THREAD

**Issue by martinmueller39** [earlyprint/earlyprint.github.io#22]
I would like to propose two changes on the splash page:

1. Replace 'read and correct' with 'read and edit'.  That lets undergraduates look forward to a career as editors rather than correction officers,

2. Replace " annotated and deeply searchable cultural archive" with "linguistically annotated and deeply searchable text archive."  I would also be happy with "linguistically annotated and  deeply searchable corpus". That language is a little more precise and gives a clearer signal about the use of corpus query tools.

**Comment by jfloewen** [comment]
I’m on board — and with either proposed version of the second suggestion.
On Nov 10, 2019, at 8:15 PM, martinmueller39 <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to propose two changes on the splash page:

  1.  Replace 'read and correct' with 'read and edit'. That lets undergraduates look forward to a career as editors rather than correction officers,

  2.  Replace " annotated and deeply searchable cultural archive" with "linguistically annotated and deeply searchable text archive." I would also be happy with "linguistically annotated and deeply searchable corpus". That language is a little more precise and gives a clearer signal about the use of corpus query tools.

**Comment by jrladd** [comment]
I can make these changes in the next day or two. I prefer "linguistically annotated and deeply searchable text archive," if no one has any objections.

Does "edit" rather than "correct" suggest a more complex procedure? I like the idea of inviting undergraduates into the process and critical thinking required for editing, but does it have the potential to intimidate students, evoking a long, multi-step process? The advantage of "correct" as I see it is that it suggests easy-to-make, atomic units of scholarly intervention.

**Comment by martinmueller39** [comment]
John,

I thought about the issue you raise about editing and understand your concern about ‘intimidate’.  But it may also encourage, and  it’s worth the risk.

On second thoughts, I also prefer ‘corpus’. It gestures towards the distinct affordances offered by a ‘corpus’ .  Here to there is a risk.  Text archive is a more comfortable term for humanists. But ‘corpus’ within the vicinity of ‘linguistic’ points to opportunities, and I think that’s worth doing

**Comment by jrladd** [comment]
Makes sense to me!
