### ISSUE TITLE
beta messsage?

### ISSUE THREAD

**Issue by martinmueller39** [earlyprint/earlyprint.github.io#28]
Should we say something explicit about the fact that EarlyPrint is still very much a work in progress and mark it as a public beta or version -.7 or something like that.  We could then add that we should aim for something that resembles completeness b y early 2021.  We can make an announcement about sgnificant improvements on the Phase I front, particularly with earlier texts. Other features, including site design, remain very much in flux.  We might also say that we are ready to err on the side of sharing stuff rather than wait until everything is perfect, which will be never

**Comment by jfloewen** [comment]
I have a single misgiving, which is that the ACLS will bristle if we tell them that we’re still beta.  I’ve asked for an extension to June 30, 2020.  Can we be past beta by then?
On Dec 5, 2019, at 3:41 PM, martinmueller39 <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we say something explicit about the fact that EarlyPrint is still very much a work in progress and mark it as a public beta or version -.7 or something like that. We could then add that we should aim for something that resembles completeness b y early 2021. We can make an announcement about sgnificant improvements on the Phase I front, particularly with earlier texts. Other features, including site design, remain very much in flux. We might also say that we are ready to err on the side of sharing stuff rather than wait until everything is perfect, which will be never

**Comment by jrladd** [comment]
Rather than beta, I might favor a message that points out that *EarlyPrint* is an ongoing work in progress, with new projects and findings showing up all the time. "Beta" implies a forthcoming stable, final version, which as @martinmueller39 points out, will never really arrive. Would such a message be less likely to cause ACLS to bristle?

**Comment by craigberry** [comment]
We haven't been in beta for some time.  There are many useful features that are working well.  We obviously have many more things we want to do, and I expect we will continue to get some of them done, but as @jrladd points out, "complete" will never really arrive.  We should continue to strive to explain to users what's available, what's been done recently, and what may be coming next. But a GitHub issue does not make that happen, so I'm closing this.
